#!/bin/bash

#dir1 - flash directory, moving files from there
#dir2 - directory on machine. Moving files into this directory
#not finished


CheckFiles()
{
back="$(pwd)"
cd "$1"

for newfiles in *
do
if [ -d $newfiles ]
then
CheckFiles "$newfiles"
elif [ $newfiles == "*" ]
then
continue
else
echo $newfiles
fi

cd "$dir2"
for oldfiles in *
do
if [ $oldfiles == $newfiles ]
then
time1= $(stat -c%Y $oldfiles)
time2= $(stat -c%Y $newfiles)
if [ $time1 > $time2 ]
then
break
fi
fi
done
cp -n -d $newfiles $dir2
done


cd $back
 
}

echo "Please, give me directory of flash driver: "
read dir1
echo "Flash directory is $dir1 "

echo "Please, give me directory of new file storage: "
read dir2
echo "Synchronization directory is $dir2 "


for files in $dir1/*
do
if [ -d $files ]
then
CheckFiles "$files"
else
echo $files*
fi
done


